name: AllMyChecklists
options:
  minimumXcodeGenVersion: 2.36.0
  bundleIdPrefix: com.neonnubula
configs:
  Debug: debug
  Release: release
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    SWIFT_VERSION: 5.9
    SUPPORTS_MACCATALYST: NO
    TARGETED_DEVICE_FAMILY: 1
packages: {}
targets:
  AllMyChecklists:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AllMyChecklists
    resources:
      - path: AllMyChecklists/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.neonnubula.allmychecklists
        PRODUCT_NAME: All My Checklists
        INFOPLIST_FILE: AllMyChecklists/Info.plist
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets:
        - AllMyChecklistsUITests
  AllMyChecklistsTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AllMyChecklistsTests
    dependencies:
      - target: AllMyChecklists
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.neonnubula.allmychecklists.tests
  AllMyChecklistsUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: AllMyChecklistsUITests
    dependencies:
      - target: AllMyChecklists
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.neonnubula.allmychecklists.uitests

